// <auto-generated />
using System;
using HangryHub.DeliveryService.Infrastructure.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HangryHub.DeliveryService.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryServiceContext))]
    [Migration("20240202095509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HangryHub.DeliveryService.Domain.DeliveryAggregate.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("HangryHub.DeliveryService.Domain.DeliveryAggregate.Delivery", b =>
                {
                    b.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.Entities.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.CustomerContact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("CustomerDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RealPhone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("VirtualPhone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("CustomerDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerDeliveryId");
                                });

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.CustomerDeliveryLocation", "DeliveryLocation", b2 =>
                                {
                                    b2.Property<Guid>("CustomerDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Address")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Note")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("CustomerDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerDeliveryId");
                                });

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.CustomerId", "Id", b2 =>
                                {
                                    b2.Property<Guid>("CustomerDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("CustomerDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerDeliveryId");
                                });

                            b1.Navigation("Contact")
                                .IsRequired();

                            b1.Navigation("DeliveryLocation")
                                .IsRequired();

                            b1.Navigation("Id")
                                .IsRequired();
                        });

                    b.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.Entities.Freelencer", "Freelencer", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TransportType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.FreelencerContact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("FreelencerDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RealPhone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("VirtualPhone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("FreelencerDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("FreelencerDeliveryId");
                                });

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.FreelencerId", "Id", b2 =>
                                {
                                    b2.Property<Guid>("FreelencerDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("FreelencerDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("FreelencerDeliveryId");
                                });

                            b1.Navigation("Contact")
                                .IsRequired();

                            b1.Navigation("Id")
                                .IsRequired();
                        });

                    b.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.Entities.Order", "Order", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.OrderId", "Id", b2 =>
                                {
                                    b2.Property<Guid>("OrderDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("OrderDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderDeliveryId");
                                });

                            b1.Navigation("Id")
                                .IsRequired();
                        });

                    b.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.Entities.Restaurant", "Restaurant", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.RestaurantContact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("RestaurantDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RealPhone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("VirtualPhone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("RestaurantDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("RestaurantDeliveryId");
                                });

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.RestaurantId", "Id", b2 =>
                                {
                                    b2.Property<Guid>("RestaurantDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("RestaurantDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("RestaurantDeliveryId");
                                });

                            b1.OwnsOne("HangryHub.DeliveryService.Domain.DeliveryAggregate.ValueObjects.RestaurantLocation", "Location", b2 =>
                                {
                                    b2.Property<Guid>("RestaurantDeliveryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Address")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("RestaurantDeliveryId");

                                    b2.ToTable("Deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("RestaurantDeliveryId");
                                });

                            b1.Navigation("Contact")
                                .IsRequired();

                            b1.Navigation("Id")
                                .IsRequired();

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Freelencer");

                    b.Navigation("Order")
                        .IsRequired();

                    b.Navigation("Restaurant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
