name: Run Tests
on:
  push:
    branches:
      - master
      - delivery_k6
  pull_request:
    branches:
      - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v3
            - uses: isbang/compose-action@v1.5.1
              with:
                compose-file: "./src/docker-compose.yml"
            - name: Wait for services to start
              run: sleep 60s    
            - name: Run K6 Tests
              uses: grafana/k6-action@v0.3.1
              with:
                filename: ./Backend/HangryHub.DeliveryService/HangryHub.DeliveryService.API/script/tests/TestGetAvaiable.js
                flags: --vus 50 --duration 10
